### ISSUE TITLE
Undefined symbols - _glutDragEventFunc

### ISSUE THREAD

**Issue by heaversm** [astellato/ofxSyphon#23]
Hi - I'm coming up with the following two issues when attempting to run the examples in oF 0.8.4 with the latest commit of syphon (c739fea5b070d0bbdb7900b9200949d4dcd64e00). I've included screenshots of the error and my project setup.

I added syphon to my build settings search paths.

![screen shot 2015-06-08 at 8 44 13 am](https://cloud.githubusercontent.com/assets/520541/8034991/f1642896-0dba-11e5-8578-c05523fef0d1.png)
![screen shot 2015-06-08 at 8 45 03 am](https://cloud.githubusercontent.com/assets/520541/8034992/f16e15e0-0dba-11e5-8f57-42260a24b5db.png)

Also, a slight correction to your readme - I believe it should say:

`addons/ofxSyphon/libs/Syphon/lib/osx`

instead of

`addons/ofxSyphon/lib/Syphon/lib/osx`

**Comment by bangnoise** [comment]
The example projects should build without any modifications - you don't need to follow the steps in the README because they have already been performed for these projects. Restore the original projects and try again. If they still don't work, it looks like GLUT isn't being linked - is GLUT.framework in the Link Binary With Libraries build phase?

**Comment by heaversm** [comment]
I think I had to build twice in order to get it to link the Syphon framework - that wasn't included automatically.
